[[language]]
name = "rust"
roots = ["Cargo.toml", "Cargo.lock", "tailwind.config.js"]
language-servers = ["rust-analyzer", "tailwindcss-ls", "emmet-ls" ]

[language-server.tailwindcss-ls]
config = { userLanguages = { rust = "html", "*.rs" = "html" } }

[language-server.rust-analyzer.config]
rustfmt = { overrideCommand = ["leptosfmt", "--stdin", "--experimental-tailwind", "--rustfmt"], procMacro = { ignored = { leptos_macro = ["server"] } } }
cargo = { features = "all" }
