[target.x86_64-unknown-linux-gnu]
# linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[unstable]
codegen-backend = true
profile-rustflags = true

[profile.server-dev]
codegen-backend = "cranelift"

[profile.dev]
rustflags = ["-Z", "threads=12", "--cfg", "erase_components", "-Awarnings"]
